export const TASKS = [
  { text: 'Celebrate a winning goal like a star striker', time: 7000 },
  { text: 'Imitate a coach arguing with the referee', time: 8000 },
  { text: 'Show how you react to a last-second three-pointer', time: 6000 },
  { text: 'Pretend you’re a goalkeeper saving a penalty', time: 7000 },
  { text: 'Do a victory dance after a big win', time: 6000 },
  { text: 'Act out a boxer walking into the ring', time: 8000 },
  { text: 'Show how a tired runner finishes a marathon', time: 7000 },
  { text: 'Act like a tennis player who just lost an easy point', time: 6000 },
  { text: 'Pretend you’re a commentator calling a crazy moment', time: 9000 },
  { text: 'Show how you celebrate winning a gold medal', time: 7000 },

  { text: 'Name three NBA teams', time: 5000 },
  { text: 'Name three football (soccer) clubs from Europe', time: 7000 },
  { text: 'Name three famous tennis players', time: 7000 },
  { text: 'Name three Olympic sports', time: 6000 },
  { text: 'Name three sports that use a ball', time: 5000 },
  { text: 'Name three sports where you run', time: 5000 },
  { text: 'Name three famous athletes from any sport', time: 8000 },
  { text: 'Name three countries that played at a World Cup', time: 8000 },
  { text: 'Name three sports where you can score with your head', time: 7000 },
  { text: 'Name three sports played on ice', time: 7000 },

  { text: 'Spell “champion” backwards', time: 7000 },
  { text: 'Say “final match” five times fast without stopping', time: 6000 },
  { text: 'Count from 5 to 1 like a referee before a fight', time: 5000 },
  { text: 'Invent a funny team name and say it out loud', time: 7000 },
  {
    text: 'Describe a sport without naming it; others must guess',
    time: 10000,
  },
  {
    text: 'Say the name of a sport for every letter: S, P, O, R, T',
    time: 10000,
  },
  { text: 'Create a short chant for your team', time: 9000 },
  { text: 'Describe how a stadium sounds during a penalty kick', time: 8000 },
  { text: 'Explain why your squad would win a tournament', time: 10000 },
  { text: 'Say three reasons why sports are fun', time: 9000 },

  { text: 'Pretend you slipped on the field but play it cool', time: 7000 },
  { text: 'Imitate a fan who just saw their team lose', time: 7000 },
  { text: 'Copy the sound of a stadium crowd getting louder', time: 8000 },
  { text: 'Act like you are juggling an invisible ball', time: 6000 },
  { text: 'Pretend you are giving a post-match interview', time: 10000 },
  { text: 'Show how you warm up before a big game', time: 8000 },
  { text: 'Act like a referee showing a red card', time: 6000 },
  { text: 'Pretend to cheer for a friend as if they scored', time: 7000 },
  { text: 'Make the face you would make after a last-second win', time: 6000 },
  {
    text: 'Act like a fan trying to find their seat in a full stadium',
    time: 9000,
  },
];
